In [1]:
import torch
import numpy as np

LIST

In [3]:
my_list=[[1,2,3,4], [1,2,3,4]]
my_list

[[1, 2, 3, 4], [1, 2, 3, 4]]

NUMPY ARRAY

In [4]:
array1=np.random.rand(3,4)
array1

array([[0.06706898, 0.19041808, 0.19382306, 0.67196755],
       [0.00937444, 0.59559636, 0.63752838, 0.11995436],
       [0.85154285, 0.68869065, 0.03100884, 0.62996893]])

In [6]:
array1.dtype

dtype('float64')

TENSOR

In [7]:
tenso_2d=torch.randn(3,4)
tenso_2d

tensor([[-0.4673, -0.1964, -0.1109, -0.5843],
        [-0.8208,  0.4404, -3.0113, -1.1211],
        [-0.8917,  1.6188, -0.4042,  0.4910]])

In [8]:
tenso_3d=torch.randn(3,4,5)
tenso_3d

tensor([[[ 7.6315e-01, -1.3653e+00,  2.2810e+00,  1.5462e-01, -2.7469e+00],
         [ 2.0479e-01, -2.7397e-01, -2.0680e-01, -1.6951e-01,  5.1619e-01],
         [-1.5936e-01,  1.1599e-01, -1.2135e+00, -2.8236e-01,  8.5061e-01],
         [-1.8346e-01, -5.2374e-01,  1.2461e+00,  1.2399e+00,  5.2316e-01]],

        [[-1.9572e-01, -4.5709e-02, -5.2993e-01,  2.1612e-01, -9.1877e-01],
         [-7.4275e-01, -8.9419e-01, -4.1695e-01,  1.1925e-01,  3.7330e-01],
         [ 5.8603e-01,  2.1015e+00,  3.1318e-01,  6.0573e-01,  2.7651e-02],
         [ 1.6003e-01,  2.1323e+00, -2.2721e-01,  1.3723e-01,  7.8908e-01]],

        [[-6.7461e-01, -2.1107e+00,  3.6622e-01, -1.2437e+00, -5.4931e-01],
         [ 5.2194e-02,  8.3331e-01,  7.8254e-01, -1.0411e+00, -1.7549e+00],
         [-3.7445e-02,  1.6410e-03, -1.0044e+00,  2.0131e-01, -7.3264e-01],
         [ 1.7031e+00, -1.5770e+00, -1.1366e+00, -1.2090e+00, -3.9592e-01]]])